#!/bin/sh

case "$1" in
    start)
    /usr/bin/aesdchar_load
    echo "loaded aesdchar module"

	;;
    stop)
    /usr/bin/aesdchar_unload
	echo "unloaded aesdchar module"

	;;
    *)
	echo "Usage : $0 {start|stop}"
    exit 1
esac

exit 0
